#server config
server:
  port: 8080
  tomcat:
    basedir: "/"

#spring config
spring:
  application:
    name: swagger-kubernetes

#swagger kubernetes config
swagger:
  kubernetes:
    connect:
      url: ${KUBERNETES_CONNECT_URL:https://kubernetes.default.svc.cluster.local}
      token: ${KUBERNETES_CONNECT_TOKEN:}
      #url: https://10.8.17.116:16443
      #token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1ibm16NCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjgzOWYyOTg3LTRmZGItMTFlOS1hZDA4LTAwNTA1NmI0NTFmZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.YmzNqSirIDHtpYFCyOUd80sWwLPz8N-2c8_NtmVw_4C3u0vEfXljoDBwcCcESKWjBbQfoQMD66na-Bmq60xWYqJeg9W0VOoqKv5BZ32wsLg1IcDBa_DjKFMVPA5g1UGkZpWn0wlhnZ4l8PI0RnG6HdGdww1pjwKZPt7R0MEXLh_l4DzAWGUfbQqNjXr2548C1Nvm3JxN6dwI-nuqTrgEx9kMeLfS6veFzjH15_el0rqvk9MOrwMufj37ajk8Imu9C4Ccy4_ZPY120Vga-KJxDMwPcG9Q0LrPllNYGhvyN8TfaGaDHiFuqHIR1iQfbQtX0ZA3ubMBi8Ts53VJc97EqQ
      #from-cluster: true
  discovery:
    namespace: ${DISCOVERY_NAMESPACE:}
    interval: ${DISCOVERY_INITIAL_INTERVAL:60}
    #${DISCOVERY-NAMESPACE:}iov-sjjh
    #url: http://10.8.17.116
    #port-type: NodePort
  global:
    docApiPath: ${API_PATH:/v2/api-docs}
    ignoreServices: ${IGNORE_SERVICES:}